#!/bin/sh

case "$2" in
    ''|now)
        TIME=0;;
    *)
        TIME="$2";;
esac

# check if invoked by symlink
# and handle appropriately
if [ $(basename $0) == 'reboot' ]; then
    kill -s INT 1
elif [ $(basename $0) == 'poweroff' ]; then
    kill -s USR1 1
# invoked by cmdline
else
    case "$1" in
#        -H|--halt)
#            sleep $TIME
#            /sbin/halt;;
    -P|--poweroff)
        if [ $TIME != 0 ]; then
            echo "System is going down for poweroff in $TIME seconds." | wall
            sleep $TIME
        fi
        kill -s USR 1
        ;;
    -r|--reboot)
        if [ $TIME != 0 ]; then
            echo "System is going down for reboot in $TIME seconds." | wall
            sleep $TIME
        fi
        kill -s INT 1
        ;;
    -c)
        echo "Shutdown cancelled." | wall
        pkill shutdown
        ;;
    *) 
        echo "Usage: shutdown <action> <time>"
        echo "actions:"
        echo "-P/--poweroff     poweroff"
        echo "-r/--reboot       reboot"
        echo "-c                cancel"
        echo "time in seconds or now"
    esac
fi
